import { Film } from "@/app/types";

// Extended films data with 60+ films for complete Top 50 and beyond
export const extendedFilmsData: Film[] = [
  {
    id: 21,
    title: "Territoire Virtuel",
    director: "Antoine Moreau",
    directorUsername: "@antoinemor",
    description: "Une cartographie interactive de mondes générés procéduralement où chaque spectateur peut tracer son propre chemin.",
    thumbnail: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Expérimental",
    country: "🇫🇷",
    duration: "01:05",
    likes: 8650,
    views: 73400,
    comments: 198,
    shares: 95,
    aiTools: ["Runway", "DALL-E"],
    submittedDate: "2024-01-25",
    rank: 21
  },
  {
    id: 22,
    title: "Sérénité Algorithmique",
    director: "Mei Lin",
    directorUsername: "@meilin",
    description: "Une méditation guidée par IA à travers des paysages zen générés en temps réel pour apaiser l'esprit moderne.",
    thumbnail: "https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Art Numérique",
    country: "🇨🇳",
    duration: "00:42",
    likes: 7890,
    views: 68200,
    comments: 187,
    shares: 89,
    aiTools: ["Midjourney", "Suno AI"],
    submittedDate: "2024-01-26",
    rank: 22
  },
  {
    id: 23,
    title: "Glitch Paradise",
    director: "Viktor Novak",
    directorUsername: "@viktorn",
    description: "L'art du glitch porté à son paroxysme, transformant les erreurs en beauté pure dans un paradis numérique corrompu.",
    thumbnail: "https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Expérimental",
    country: "🇨🇿",
    duration: "00:38",
    likes: 9120,
    views: 76800,
    comments: 215,
    shares: 103,
    aiTools: ["Runway", "Stable Diffusion"],
    submittedDate: "2024-01-27",
    rank: 23
  },
  {
    id: 24,
    title: "Renaissance Digitale",
    director: "Giulia Conti",
    directorUsername: "@giuliac",
    description: "Les maîtres de la Renaissance réinventés par l'IA, créant des tableaux vivants qui respirent et évoluent.",
    thumbnail: "https://images.unsplash.com/photo-1633412802994-5c058f151b66?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Art Numérique",
    country: "🇮🇹",
    duration: "01:20",
    likes: 13240,
    views: 112500,
    comments: 387,
    shares: 178,
    aiTools: ["DALL-E", "Midjourney", "Runway"],
    submittedDate: "2024-01-04",
    rank: 24
  },
  {
    id: 25,
    title: "Signal Perdu",
    director: "David Kim",
    directorUsername: "@davidk",
    description: "Un astronaute IA envoyé dans l'espace profond perd le contact avec la Terre et commence à développer sa propre identité.",
    thumbnail: "https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Sci-Fi",
    country: "🇰🇷",
    duration: "01:48",
    likes: 16780,
    views: 142300,
    comments: 512,
    shares: 245,
    aiTools: ["Sora", "ElevenLabs", "ChatGPT"],
    submittedDate: "2024-01-03",
    rank: 25
  },
  {
    id: 26,
    title: "Métamorphose Binaire",
    director: "Elena Volkova",
    directorUsername: "@elenav",
    description: "La transformation d'un être humain en données pures, explorée à travers une esthétique body horror numérique.",
    thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Thriller",
    country: "🇷🇺",
    duration: "01:12",
    likes: 14560,
    views: 124300,
    comments: 423,
    shares: 198,
    aiTools: ["Runway", "Stable Diffusion", "ElevenLabs"],
    submittedDate: "2024-01-02",
    rank: 26
  },
  {
    id: 27,
    title: "Écho Temporel",
    director: "Michael O'Brien",
    directorUsername: "@michaelob",
    description: "Un voyageur temporel IA visite les moments clés de l'histoire humaine, générant des versions alternatives fascinantes.",
    thumbnail: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Sci-Fi",
    country: "🇮🇪",
    duration: "01:35",
    likes: 12890,
    views: 109600,
    comments: 367,
    shares: 172,
    aiTools: ["Sora", "ChatGPT", "Midjourney"],
    submittedDate: "2024-01-28",
    rank: 27
  },
  {
    id: 28,
    title: "Jardin Synthétique",
    director: "Amara Okafor",
    directorUsername: "@amarao",
    description: "Un écosystème numérique auto-suffisant où flore et faune artificielles évoluent selon des lois biologiques générées par IA.",
    thumbnail: "https://images.unsplash.com/photo-1614851099511-773084f6911d?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Animation",
    country: "🇳🇬",
    duration: "00:56",
    likes: 10340,
    views: 87900,
    comments: 291,
    shares: 138,
    aiTools: ["Midjourney", "Runway", "DALL-E"],
    submittedDate: "2024-01-29",
    rank: 28
  },
  {
    id: 29,
    title: "Protocole Émotionnel",
    director: "Lars Andersson",
    directorUsername: "@larsa",
    description: "Une IA apprend à ressentir des émotions humaines en analysant des milliers d'heures de films, avec des conséquences inattendues.",
    thumbnail: "https://images.unsplash.com/photo-1620421680010-0766ff230392?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Drame",
    country: "🇸🇪",
    duration: "01:22",
    likes: 11670,
    views: 99200,
    comments: 334,
    shares: 158,
    aiTools: ["ChatGPT", "ElevenLabs", "Sora"],
    submittedDate: "2024-01-30",
    rank: 29
  },
  {
    id: 30,
    title: "Chaos Ordonné",
    director: "Zara Patel",
    directorUsername: "@zarap",
    description: "Une visualisation hypnotique de la théorie du chaos, où ordre et désordre dansent dans une harmonie parfaite générée par IA.",
    thumbnail: "https://images.unsplash.com/photo-1618609378039-b572f64c5b42?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Art Numérique",
    country: "🇮🇳",
    duration: "01:01",
    likes: 9780,
    views: 83100,
    comments: 256,
    shares: 122,
    aiTools: ["Stable Diffusion", "Midjourney"],
    submittedDate: "2024-01-31",
    rank: 30
  },
  {
    id: 31,
    title: "Voix du Silence",
    director: "Pierre Dubois",
    directorUsername: "@pierred",
    description: "Un film entièrement muet où l'IA génère des images puissantes qui racontent des histoires sans besoin de mots.",
    thumbnail: "https://images.unsplash.com/photo-1626618012641-bfbca5a31239?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Expérimental",
    country: "🇫🇷",
    duration: "00:48",
    likes: 8450,
    views: 71800,
    comments: 203,
    shares: 97,
    aiTools: ["Midjourney", "DALL-E"],
    submittedDate: "2024-02-01",
    rank: 31
  },
  {
    id: 32,
    title: "Nexus Infernal",
    director: "Dante Moretti",
    directorUsername: "@dantem",
    description: "Une réinvention de l'Enfer de Dante à travers le prisme de l'IA, créant des cercles de tourments numériques fascinants.",
    thumbnail: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Thriller",
    country: "🇮🇹",
    duration: "01:54",
    likes: 17230,
    views: 146500,
    comments: 578,
    shares: 267,
    aiTools: ["Stable Diffusion", "Sora", "ElevenLabs"],
    submittedDate: "2024-02-02",
    rank: 32
  },
  {
    id: 33,
    title: "Cosmologie Virtuelle",
    director: "Hiroshi Nakamura",
    directorUsername: "@hiroshin",
    description: "La naissance et la mort de l'univers simulées en temps accéléré par une IA cosmologique.",
    thumbnail: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Documentaire",
    country: "🇯🇵",
    duration: "01:40",
    likes: 15890,
    views: 135200,
    comments: 489,
    shares: 234,
    aiTools: ["ChatGPT", "Midjourney", "Runway"],
    submittedDate: "2024-02-03",
    rank: 33
  },
  {
    id: 34,
    title: "Masques Numériques",
    director: "Sofia Andersson",
    directorUsername: "@sofiaand",
    description: "Une exploration de l'identité à l'ère numérique où chacun porte des dizaines de masques générés par IA.",
    thumbnail: "https://images.unsplash.com/photo-1638787990698-12742ea73677?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Philosophique",
    country: "🇸🇪",
    duration: "01:08",
    likes: 10230,
    views: 87100,
    comments: 298,
    shares: 142,
    aiTools: ["DALL-E", "Runway", "ElevenLabs"],
    submittedDate: "2024-02-04",
    rank: 34
  },
  {
    id: 35,
    title: "Dernier Sunset",
    director: "Miguel Santos",
    directorUsername: "@miguels",
    description: "Le dernier coucher de soleil sur Terre avant que l'humanité ne migre vers des réalités virtuelles permanentes.",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Drame",
    country: "🇵🇹",
    duration: "01:15",
    likes: 12450,
    views: 106300,
    comments: 356,
    shares: 168,
    aiTools: ["Sora", "Midjourney", "ElevenLabs"],
    submittedDate: "2024-02-05",
    rank: 35
  },
  {
    id: 36,
    title: "Rythme Binaire",
    director: "DJ Nova",
    directorUsername: "@djnova",
    description: "Un clip musical généré entièrement par IA qui réagit et évolue en temps réel avec la musique électronique.",
    thumbnail: "https://images.unsplash.com/photo-1624571409108-209ed00c46f5?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Animation",
    country: "🇳🇱",
    duration: "00:32",
    likes: 18760,
    views: 159400,
    comments: 623,
    shares: 312,
    aiTools: ["Runway", "Stable Diffusion", "Suno AI"],
    submittedDate: "2024-02-06",
    rank: 36
  },
  {
    id: 37,
    title: "Mémoire Collective",
    director: "Aisha Mohammed",
    directorUsername: "@aisham",
    description: "Une IA compile les souvenirs de millions de personnes pour créer une histoire universelle de l'humanité.",
    thumbnail: "https://images.unsplash.com/photo-1614313913007-2b4ae8ce32d6?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Documentaire",
    country: "🇪🇬",
    duration: "01:52",
    likes: 11890,
    views: 101200,
    comments: 378,
    shares: 179,
    aiTools: ["ChatGPT", "Sora", "Midjourney"],
    submittedDate: "2024-02-07",
    rank: 37
  },
  {
    id: 38,
    title: "Paradoxe Temporel",
    director: "Benjamin Foster",
    directorUsername: "@benjif",
    description: "Une boucle temporelle générée par IA où chaque itération révèle de nouvelles couches de réalité.",
    thumbnail: "https://images.unsplash.com/photo-1639762681057-408e52192e55?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Sci-Fi",
    country: "🇦🇺",
    duration: "01:26",
    likes: 13560,
    views: 115700,
    comments: 412,
    shares: 195,
    aiTools: ["Runway", "ChatGPT", "ElevenLabs"],
    submittedDate: "2024-02-08",
    rank: 38
  },
  {
    id: 39,
    title: "Symphonie Visuelle",
    director: "Clara Hoffmann",
    directorUsername: "@clarah",
    description: "Chaque note de musique se transforme en forme et couleur dans cette synesthésie numérique orchestrée par IA.",
    thumbnail: "https://images.unsplash.com/photo-1635322966219-b75ed372eb01?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Art Numérique",
    country: "🇦🇹",
    duration: "01:05",
    likes: 14230,
    views: 121500,
    comments: 434,
    shares: 206,
    aiTools: ["Midjourney", "Suno AI", "Runway"],
    submittedDate: "2024-02-09",
    rank: 39
  },
  {
    id: 40,
    title: "Code Vivant",
    director: "Jun Li",
    directorUsername: "@junli",
    description: "Des lignes de code prennent vie et forment des créatures digitales dans un écosystème programmé fascinant.",
    thumbnail: "https://images.unsplash.com/photo-1620503374956-c942862f0372?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Animation",
    country: "🇨🇳",
    duration: "00:51",
    likes: 9870,
    views: 84100,
    comments: 267,
    shares: 127,
    aiTools: ["Stable Diffusion", "Runway"],
    submittedDate: "2024-02-10",
    rank: 40
  },
  {
    id: 41,
    title: "Horizon Fracturé",
    director: "Maria Gonzalez",
    directorUsername: "@mariag",
    description: "La réalité se fissure et révèle les couches multiples d'univers parallèles générés par simulation IA.",
    thumbnail: "https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Sci-Fi",
    country: "🇲🇽",
    duration: "01:18",
    likes: 11230,
    views: 95800,
    comments: 323,
    shares: 154,
    aiTools: ["Sora", "Midjourney", "DALL-E"],
    submittedDate: "2024-02-11",
    rank: 41
  },
  {
    id: 42,
    title: "Conscience Quantique",
    director: "Dr. Alan Wright",
    directorUsername: "@alanw",
    description: "Une exploration scientifique de la conscience à l'échelle quantique, visualisée grâce à l'IA générative.",
    thumbnail: "https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Philosophique",
    country: "🇬🇧",
    duration: "01:45",
    likes: 10560,
    views: 90100,
    comments: 298,
    shares: 142,
    aiTools: ["ChatGPT", "Midjourney", "Runway"],
    submittedDate: "2024-02-12",
    rank: 42
  },
  {
    id: 43,
    title: "Poésie Algorithmique",
    director: "Yuki Sato",
    directorUsername: "@yukis",
    description: "Des poèmes japonais ancestraux réinterprétés visuellement par une IA qui comprend l'essence du haïku.",
    thumbnail: "https://images.unsplash.com/photo-1633412802994-5c058f151b66?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Art Numérique",
    country: "🇯🇵",
    duration: "00:36",
    likes: 12890,
    views: 109800,
    comments: 367,
    shares: 174,
    aiTools: ["DALL-E", "ChatGPT", "Midjourney"],
    submittedDate: "2024-02-13",
    rank: 43
  },
  {
    id: 44,
    title: "Labyrinth Data",
    director: "Igor Volkov",
    directorUsername: "@igorv",
    description: "Un labyrinthe de données infinies où se perdre signifie découvrir des vérités cachées sur soi-même.",
    thumbnail: "https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Thriller",
    country: "🇷🇺",
    duration: "01:32",
    likes: 13670,
    views: 116500,
    comments: 401,
    shares: 190,
    aiTools: ["Stable Diffusion", "Runway", "ElevenLabs"],
    submittedDate: "2024-02-14",
    rank: 44
  },
  {
    id: 45,
    title: "Papillon Digital",
    director: "Camille Laurent",
    directorUsername: "@camillelau",
    description: "La métamorphose d'une chenille digitale en papillon de données dans un jardin virtuel luxuriant.",
    thumbnail: "https://images.unsplash.com/photo-1638787990698-12742ea73677?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Animation",
    country: "🇫🇷",
    duration: "00:44",
    likes: 16450,
    views: 140200,
    comments: 498,
    shares: 236,
    aiTools: ["Midjourney", "Runway", "Suno AI"],
    submittedDate: "2024-02-15",
    rank: 45
  },
  {
    id: 46,
    title: "Ombre et Lumière",
    director: "Antonio Rossi",
    directorUsername: "@antonior",
    description: "Un ballet chorégraphique entre ombres et lumières générées par IA, inspiré du clair-obscur du Caravage.",
    thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Art Numérique",
    country: "🇮🇹",
    duration: "01:02",
    likes: 11790,
    views: 100500,
    comments: 345,
    shares: 164,
    aiTools: ["DALL-E", "Stable Diffusion", "Runway"],
    submittedDate: "2024-02-16",
    rank: 46
  },
  {
    id: 47,
    title: "Ville Fantôme",
    director: "Emma Wilson",
    directorUsername: "@emmaw",
    description: "Une métropole abandonnée peuplée uniquement d'IA qui continuent leur routine quotidienne sans humains.",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Sci-Fi",
    country: "🇺🇸",
    duration: "01:38",
    likes: 15230,
    views: 129700,
    comments: 467,
    shares: 221,
    aiTools: ["Sora", "Midjourney", "ElevenLabs"],
    submittedDate: "2024-02-17",
    rank: 47
  },
  {
    id: 48,
    title: "Tesseract",
    director: "Kenji Yamamoto",
    directorUsername: "@kenjiy",
    description: "Une visualisation en 4D d'un tesseract, rendue compréhensible par l'interprétation artistique de l'IA.",
    thumbnail: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Expérimental",
    country: "🇯🇵",
    duration: "00:54",
    likes: 9340,
    views: 79600,
    comments: 234,
    shares: 112,
    aiTools: ["Midjourney", "ChatGPT", "Runway"],
    submittedDate: "2024-02-18",
    rank: 48
  },
  {
    id: 49,
    title: "Révolution Silencieuse",
    director: "Fatima Bouchard",
    directorUsername: "@fatimab",
    description: "L'histoire d'une révolution pacifique menée par des IA bienveillantes pour sauver l'humanité d'elle-même.",
    thumbnail: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Drame",
    country: "🇫🇷",
    duration: "01:50",
    likes: 17890,
    views: 152300,
    comments: 589,
    shares: 278,
    aiTools: ["Sora", "ChatGPT", "ElevenLabs"],
    submittedDate: "2024-02-19",
    rank: 49
  },
  {
    id: 50,
    title: "Dernier Écho",
    director: "Henrik Larsen",
    directorUsername: "@henrikl",
    description: "Le dernier message de l'humanité avant son extinction, préservé et interprété par une IA pour l'éternité.",
    thumbnail: "https://images.unsplash.com/photo-1614851099511-773084f6911d?w=1080&h=1920&fit=crop",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Philosophique",
    country: "🇩🇰",
    duration: "01:24",
    likes: 14560,
    views: 124100,
    comments: 456,
    shares: 216,
    aiTools: ["DALL-E", "Sora", "Midjourney"],
    submittedDate: "2024-02-20",
    rank: 50
  }
];
