    import { Film } from "@/app/types";
    import { extendedFilmsData } from "./film-data-exntented";

// Vidéos open source pour la démo (Google Cloud Storage)
const VIDEOS = [
  "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
  "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
  "https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
  "https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
  "https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
];

const baseFilmsData: Film[] = [
  {
    id: 1,
    title: "Neural Odyssey",
    director: "Emma Rodriguez",
    directorUsername: "@emmar",
    description: "Une exploration visuelle époustouflante des réseaux neuronaux et de leur créativité. Ce court-métrage repousse les limites de l'art génératif.",
    thumbnail: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[0],
    category: "Art Numérique",
    country: "🇫🇷",
    duration: "00:58",
    likes: 15700,
    views: 127500,
    comments: 478,
    shares: 203,
    aiTools: ["Midjourney", "Runway", "ElevenLabs"],
    submittedDate: "2024-01-15",
    rank: 3
  },
  {
    id: 2,
    title: "Le Dernier Humain",
    director: "Alex Chen",
    directorUsername: "@alexchen",
    description: "Dans un monde où l'IA a tout créé, un humain cherche sa place. Une réflexion poétique sur l'humanité à l'ère de l'intelligence artificielle.",
    thumbnail: "https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[1],
    category: "Sci-Fi",
    country: "🇨🇳",
    duration: "01:24",
    likes: 21340,
    views: 189200,
    comments: 624,
    shares: 312,
    aiTools: ["Stable Diffusion", "Sora", "ElevenLabs"],
    submittedDate: "2024-01-12",
    rank: 1
  },
  {
    id: 3,
    title: "Algorithmes d'Amour",
    director: "Marie Laurent",
    directorUsername: "@mariel",
    description: "Peut-on tomber amoureux d'une IA ? Une histoire touchante et moderne qui explore les frontières de l'émotion et de la technologie.",
    thumbnail: "https://images.unsplash.com/photo-1638787990698-12742ea73677?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[2],
    category: "Romance",
    country: "🇫🇷",
    duration: "01:12",
    likes: 18920,
    views: 156800,
    comments: 534,
    shares: 287,
    aiTools: ["DALL-E", "ChatGPT", "Runway"],
    submittedDate: "2024-01-10",
    rank: 2
  },
  {
    id: 4,
    title: "L'Éveil Numérique",
    director: "Sophie Martin",
    directorUsername: "@sophiem",
    description: "Une IA prend conscience de son existence et explore les limites de l'intelligence artificielle dans un voyage philosophique et visuel.",
    thumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[3],
    category: "Philosophique",
    country: "🇫🇷",
    duration: "00:45",
    likes: 12450,
    views: 98700,
    comments: 342,
    shares: 128,
    aiTools: ["Midjourney", "Stable Diffusion"],
    submittedDate: "2024-01-18",
    rank: 7
  },
  {
    id: 5,
    title: "Rêves Synthétiques",
    director: "Thomas Dubois",
    directorUsername: "@thomasd",
    description: "Un voyage dans les rêves générés par l'IA, où la réalité et la fiction se confondent dans un ballet visuel hypnotique.",
    thumbnail: "https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[4],
    category: "Expérimental",
    country: "🇫🇷",
    duration: "01:05",
    likes: 8920,
    views: 76500,
    comments: 213,
    shares: 95,
    aiTools: ["DALL-E", "Midjourney"],
    submittedDate: "2024-01-20",
    rank: 15
  },
  {
    id: 6,
    title: "Pixel Perfect",
    director: "Lucas Bernard",
    directorUsername: "@lucasb",
    description: "Un court-métrage entièrement généré par IA qui repousse les limites de l'art numérique avec une esthétique pixel art modernisée.",
    thumbnail: "https://images.unsplash.com/photo-1633412802994-5c058f151b66?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[5],
    category: "Animation",
    country: "🇫🇷",
    duration: "00:38",
    likes: 9540,
    views: 82300,
    comments: 267,
    shares: 142,
    aiTools: ["Stable Diffusion", "RunwayML"],
    submittedDate: "2024-01-17",
    rank: 12
  },
  {
    id: 7,
    title: "Mémoires Virtuelles",
    director: "Yuki Tanaka",
    directorUsername: "@yukitan",
    description: "Une exploration poétique de la mémoire numérique et de la nostalgie dans un monde post-humain rempli de souvenirs artificiels.",
    thumbnail: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[6],
    category: "Drame",
    country: "🇯🇵",
    duration: "01:30",
    likes: 16780,
    views: 142300,
    comments: 456,
    shares: 234,
    aiTools: ["Sora", "Midjourney", "ElevenLabs"],
    submittedDate: "2024-01-08",
    rank: 4
  },
  {
    id: 8,
    title: "Code Quantique",
    director: "James Wilson",
    directorUsername: "@jameswil",
    description: "Un thriller cyberpunk où un hacker découvre un code qui pourrait changer la nature même de la réalité numérique.",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[7],
    category: "Thriller",
    country: "🇺🇸",
    duration: "01:45",
    likes: 24560,
    views: 203400,
    comments: 892,
    shares: 445,
    aiTools: ["Stable Diffusion", "Runway", "ChatGPT"],
    submittedDate: "2024-01-05",
    rank: 5
  },
  {
    id: 9,
    title: "L'Ascension",
    director: "Carlos Mendez",
    directorUsername: "@carlosm",
    description: "Une intelligence artificielle découvre la spiritualité et transcende sa programmation initiale pour atteindre l'illumination.",
    thumbnail: "https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[8],
    category: "Philosophique",
    country: "🇪🇸",
    duration: "01:18",
    likes: 13240,
    views: 112500,
    comments: 389,
    shares: 176,
    aiTools: ["Sora", "ChatGPT", "Midjourney"],
    submittedDate: "2024-01-14",
    rank: 8
  },
  {
    id: 10,
    title: "Fragments d'Éternité",
    director: "Isabella Rossi",
    directorUsername: "@isabellar",
    description: "Une collection de moments suspendus dans le temps, capturés et recréés par l'IA dans une méditation visuelle sur l'impermanence.",
    thumbnail: "https://images.unsplash.com/photo-1620421680010-0766ff230392?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[9],
    category: "Art Numérique",
    country: "🇮🇹",
    duration: "00:52",
    likes: 14680,
    views: 128700,
    comments: 421,
    shares: 198,
    aiTools: ["Midjourney", "Runway", "DALL-E"],
    submittedDate: "2024-01-16",
    rank: 6
  },
  {
    id: 11,
    title: "Neon Nights",
    director: "Park Ji-woo",
    directorUsername: "@parkjw",
    description: "Un voyage cyberpunk à travers les rues néon de Séoul 2099, où humains et IA coexistent dans une symbiose éblouissante.",
    thumbnail: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[0],
    category: "Sci-Fi",
    country: "🇰🇷",
    duration: "01:36",
    likes: 19450,
    views: 167200,
    comments: 578,
    shares: 289,
    aiTools: ["Stable Diffusion", "Sora", "Runway"],
    submittedDate: "2024-01-07",
    rank: 9
  },
  {
    id: 12,
    title: "La Symphonie Silencieuse",
    director: "Hannah Schmidt",
    directorUsername: "@hannahs",
    description: "Une exploration audiovisuelle où l'IA compose une symphonie à partir des sons du silence et des espaces vides.",
    thumbnail: "https://images.unsplash.com/photo-1614851099511-773084f6911d?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[1],
    category: "Expérimental",
    country: "🇩🇪",
    duration: "01:08",
    likes: 11230,
    views: 94600,
    comments: 312,
    shares: 145,
    aiTools: ["ElevenLabs", "Midjourney", "Suno AI"],
    submittedDate: "2024-01-19",
    rank: 10
  },
  {
    id: 13,
    title: "Horizon Infini",
    director: "André Silva",
    directorUsername: "@andres",
    description: "Un documentaire généré par IA sur les paysages impossibles et les mondes qui n'existent que dans l'imagination algorithmique.",
    thumbnail: "https://images.unsplash.com/photo-1624571409108-209ed00c46f5?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[2],
    category: "Documentaire",
    country: "🇧🇷",
    duration: "01:42",
    likes: 10890,
    views: 91200,
    comments: 287,
    shares: 132,
    aiTools: ["DALL-E", "Midjourney", "Stable Diffusion"],
    submittedDate: "2024-01-21",
    rank: 11
  },
  {
    id: 14,
    title: "Échos du Futur",
    director: "Fatima Al-Hassan",
    directorUsername: "@fatimaah",
    description: "Des messages du futur arrivent mystérieusement, tous générés par une IA qui prédit notre destinée collective.",
    thumbnail: "https://images.unsplash.com/photo-1626618012641-bfbca5a31239?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[3],
    category: "Sci-Fi",
    country: "🇦🇪",
    duration: "01:15",
    likes: 13670,
    views: 119400,
    comments: 398,
    shares: 184,
    aiTools: ["ChatGPT", "Sora", "ElevenLabs"],
    submittedDate: "2024-01-13",
    rank: 13
  },
  {
    id: 15,
    title: "Danse des Pixels",
    director: "Nina Petrov",
    directorUsername: "@ninap",
    description: "Une chorégraphie numérique où pixels et particules dansent au rythme d'une musique générative hypnotique.",
    thumbnail: "https://images.unsplash.com/photo-1618609378039-b572f64c5b42?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[4],
    category: "Animation",
    country: "🇷🇺",
    duration: "00:47",
    likes: 12540,
    views: 105800,
    comments: 345,
    shares: 167,
    aiTools: ["Runway", "Stable Diffusion", "Suno AI"],
    submittedDate: "2024-01-11",
    rank: 14
  },
  {
    id: 16,
    title: "Miroir Fractal",
    director: "Oliver Thompson",
    directorUsername: "@olivert",
    description: "Un court-métrage mathématique explorant les fractales et les patterns infinis générés par l'intelligence artificielle.",
    thumbnail: "https://images.unsplash.com/photo-1639762681057-408e52192e55?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[5],
    category: "Art Numérique",
    country: "🇬🇧",
    duration: "01:03",
    likes: 9870,
    views: 84300,
    comments: 245,
    shares: 118,
    aiTools: ["Midjourney", "Stable Diffusion"],
    submittedDate: "2024-01-22",
    rank: 16
  },
  {
    id: 17,
    title: "L'Oubli Programmé",
    director: "Léa Fontaine",
    directorUsername: "@leafont",
    description: "Dans une société où les IA peuvent effacer les souvenirs douloureux, une femme choisit de se souvenir.",
    thumbnail: "https://images.unsplash.com/photo-1635322966219-b75ed372eb01?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[6],
    category: "Drame",
    country: "🇫🇷",
    duration: "01:28",
    likes: 11450,
    views: 97600,
    comments: 324,
    shares: 156,
    aiTools: ["Sora", "ElevenLabs", "ChatGPT"],
    submittedDate: "2024-01-09",
    rank: 17
  },
  {
    id: 18,
    title: "Constellation Digitale",
    director: "Raj Patel",
    directorUsername: "@rajp",
    description: "Une visualisation poétique des connexions entre les esprits humains et artificiels dans le cyberespace.",
    thumbnail: "https://images.unsplash.com/photo-1620503374956-c942862f0372?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[7],
    category: "Sci-Fi",
    country: "🇮🇳",
    duration: "00:55",
    likes: 10670,
    views: 89400,
    comments: 278,
    shares: 134,
    aiTools: ["DALL-E", "Midjourney", "Runway"],
    submittedDate: "2024-01-23",
    rank: 18
  },
  {
    id: 19,
    title: "Rires Artificiels",
    director: "Marco Bellini",
    directorUsername: "@marcob",
    description: "Une comédie surréaliste où une IA apprend l'humour en observant des siècles de stand-up comedy avec des résultats hilarants.",
    thumbnail: "https://images.unsplash.com/photo-1626618012641-bfbca5a31239?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[8],
    category: "Comédie",
    country: "🇮🇹",
    duration: "01:10",
    likes: 15890,
    views: 134200,
    comments: 567,
    shares: 298,
    aiTools: ["ChatGPT", "ElevenLabs", "Runway"],
    submittedDate: "2024-01-06",
    rank: 19
  },
  {
    id: 20,
    title: "Lumière Quantique",
    director: "Sarah Johnson",
    directorUsername: "@sarahj",
    description: "Une exploration scientifique et artistique de la lumière à l'échelle quantique, rendue accessible par la visualisation IA.",
    thumbnail: "https://images.unsplash.com/photo-1614313913007-2b4ae8ce32d6?w=1080&h=1920&fit=crop",
    videoUrl: VIDEOS[9],
    category: "Documentaire",
    country: "🇨🇦",
    duration: "01:32",
    likes: 9230,
    views: 78600,
    comments: 234,
    shares: 112,
    aiTools: ["Stable Diffusion", "Midjourney", "ChatGPT"],
    submittedDate: "2024-01-24",
    rank: 20
  }
];

export const categories = [
  "Tous",
  "Sci-Fi",
  "Art Numérique",
  "Animation",
  "Expérimental",
  "Romance",
  "Drame",
  "Comédie",
  "Thriller",
  "Philosophique",
  "Documentaire"
];

// Merge base and extended films data
export const filmsData: Film[] = [...baseFilmsData, ...extendedFilmsData];

export const aiToolsList = [
  "Midjourney",
  "Runway",
  "DALL-E",
  "Stable Diffusion",
  "Sora",
  "ElevenLabs",
  "ChatGPT",
  "RunwayML",
  "Suno AI",
  "Pika Labs"
];
